package com.chasemaster.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Dec 17 21:17:26 GMT 2012
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://ws.chasemaster.com/", name = "ChasemasterController")
@XmlSeeAlso({ObjectFactory.class})
public interface ChasemasterController {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://ws.chasemaster.com/", className = "com.chasemaster.ws.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://ws.chasemaster.com/", className = "com.chasemaster.ws.RegisterResponse")
    @WebMethod
    public java.lang.String register(
        @WebParam(name = "User", targetNamespace = "")
        com.chasemaster.ws.client.User user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.chasemaster.com/", className = "com.chasemaster.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.chasemaster.com/", className = "com.chasemaster.ws.LoginResponse")
    @WebMethod
    public com.chasemaster.ws.client.Response login(
        @WebParam(name = "UserCredentials", targetNamespace = "")
        com.chasemaster.ws.client.UserCredentials userCredentials
    );
}
