
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.chasemaster.ws.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Dec 17 21:17:26 GMT 2012
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ChasemasterControllerImplService",
                      portName = "ChasemasterControllerImplPort",
                      targetNamespace = "http://ws.chasemaster.com/",
                      wsdlLocation = "http://localhost:8080/Chasemaster/ws/Service?wsdl",
                      endpointInterface = "com.chasemaster.ws.ChasemasterController")
                      
public class ChasemasterControllerImpl implements ChasemasterController {

    private static final Logger LOG = Logger.getLogger(ChasemasterControllerImpl.class.getName());

    /* (non-Javadoc)
     * @see com.chasemaster.ws.ChasemasterController#register(com.chasemaster.ws.User  user )*
     */
    public java.lang.String register(com.chasemaster.ws.client.User user) { 
        LOG.info("Executing operation register");
        System.out.println(user);
        try {
            java.lang.String _return = "_return1148149314";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.chasemaster.ws.ChasemasterController#login(com.chasemaster.ws.UserCredentials  userCredentials )*
     */
    public com.chasemaster.ws.client.Response login(com.chasemaster.ws.client.UserCredentials userCredentials) { 
        LOG.info("Executing operation login");
        System.out.println(userCredentials);
        try {
            com.chasemaster.ws.client.Response _return = new com.chasemaster.ws.client.Response();
            _return.setMessageText("MessageText-459422673");
            _return.setMessageType("MessageType1205362754");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
