
package com.chasemaster.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Dec 17 21:17:26 GMT 2012
 * Generated source version: 2.2.6
 * 
 */

public final class ChasemasterController_ChasemasterControllerImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.chasemaster.com/", "ChasemasterControllerImplService");

    private ChasemasterController_ChasemasterControllerImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ChasemasterControllerImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ChasemasterControllerImplService ss = new ChasemasterControllerImplService(wsdlURL, SERVICE_NAME);
        ChasemasterController port = ss.getChasemasterControllerImplPort();  
        
        {
        System.out.println("Invoking register...");
        com.chasemaster.ws.client.User _register_user = new com.chasemaster.ws.client.User();
        _register_user.setUsername("Username2041268439");
        _register_user.setPassword("Password-234650379");
        _register_user.setPasswordConfirmation("PasswordConfirmation1805457817");
        _register_user.setEMail("EMail-1696129035");
        java.lang.String _register__return = port.register(_register_user);
        System.out.println("register.result=" + _register__return);


        }
        {
        System.out.println("Invoking login...");
        com.chasemaster.ws.client.UserCredentials _login_userCredentials = new com.chasemaster.ws.client.UserCredentials();
        _login_userCredentials.setUsername("Username1646995103");
        _login_userCredentials.setPassword("Password-930692319");
        com.chasemaster.ws.client.Response _login__return = port.login(_login_userCredentials);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
