
/*
 * 
 */

package com.chasemaster.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Dec 17 21:17:26 GMT 2012
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "ChasemasterControllerImplService", 
                  wsdlLocation = "http://localhost:8080/Chasemaster/ws/Service?wsdl",
                  targetNamespace = "http://ws.chasemaster.com/") 
public class ChasemasterControllerImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.chasemaster.com/", "ChasemasterControllerImplService");
    public final static QName ChasemasterControllerImplPort = new QName("http://ws.chasemaster.com/", "ChasemasterControllerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Chasemaster/ws/Service?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/Chasemaster/ws/Service?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ChasemasterControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChasemasterControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChasemasterControllerImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ChasemasterController
     */
    @WebEndpoint(name = "ChasemasterControllerImplPort")
    public ChasemasterController getChasemasterControllerImplPort() {
        return super.getPort(ChasemasterControllerImplPort, ChasemasterController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChasemasterController
     */
    @WebEndpoint(name = "ChasemasterControllerImplPort")
    public ChasemasterController getChasemasterControllerImplPort(WebServiceFeature... features) {
        return super.getPort(ChasemasterControllerImplPort, ChasemasterController.class, features);
    }

}
